{% set name = "absl-py" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/absl-py-{{ version }}.tar.gz
  sha256: d9690211c5fcfefcdd1a45470ac2b5c5acd45241c3af71eed96bc5441746c0d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - ez_setup
    - pip
  run:
    - python >=3.6

test:
  imports:
    - absl
    - absl.flags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abseil/abseil-py
  summary: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://abseil.io/docs/
  dev_url: https://github.com/abseil/abseil-py

extra:
  recipe-maintainers:
    - ocefpaf
