{% set name = "absl-py" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bf25b2c2eed013ca456918c453d687eab4e8309fba81ee2f4c1a6aa2494175eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - ez_setup
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - absl
    - absl.flags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/abseil/abseil-py
  summary: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://abseil.io/docs/
  dev_url: https://github.com/abseil/abseil-py

extra:
  recipe-maintainers:
    - ocefpaf
