appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CnYXtUMfScKgmH4VOXkH6OaysdlR84ld/cyDj0efykSX05BVLE2Fc04Qj7RiHbr9QAwBQiY3QLTNmZ/Ly+9419B3KMabStSB07wSGsYIegnop+iXlKR+HhWq+KWrbrZ+yTsRixTOtq0Ex1ZacsvIUwV+Xtr6Vy6+v9SmZDnTEWHDdkzidl9V5gSSeFikLCcw4c2Fs6ddDwV5eY4618JGCyU2pobgO3dMGZwe49n80ydmwLqAdUDgfnxHVzNPyCCEdK8OBrNMupXQWeUg+9uAnM7OpQAhLn9z16TXZbFqOoX6WfKGWvabucsrdIvxUpepFBqfd5FprBYHcWUBddYVFBWW26UJ0WPKbTeJuIpcEIhKxrjnLtGFOzYO6KsJjeGJfC7I+oTEdrRfgXJPPtC+8B9VoG3EYOXgTVz7pdbGvZAo8zJO8EhQ9sVRJbpHMd6a6xrtZ5ibS9HqLg/yL+078Mgey7cZCe1GEYIUTyCW4lMKGTEe2uoY4LOxg5nz3+S1XHlY56+eqA845BF+U2ocRirTtpdGYUpJXYNW7iIVTbQ+Hk2XmEgJVSPCz7qz3KaYbhtmMY4kEGp633joPxeP9pWOeV7p0LrDpFm6RlCL2Y2CppkidxN1GeiRKIAOzlJNgF4fkPdu+knSNopRGR7ODYEXH9qNhwmfTfMumLAA24g=}
